travis:
  secure:
    BINSTAR_TOKEN: peOUTRcGMeLEUhsfyIUev93LDsDn0MNj9yprgeqTEaQM5hkv5NcyQi8iS9OQjBvCQBCQwe890PNfKSnHeQc0HP4ycHFOGiVHj4pCogbnei1IKrjZZT3q/UYw4p/jNwssqRTtkCAYuUSsVrT8MlG0jr2/7noik3qB4F3kvi/CAjEcfs282lVyvN2hKExwzHiro16tEfxgLO4a550TdvJM6Ybvcmm+Y8fBmn16Rg71acYpnk6QUI+EO11SVsi0Xt37j24cJZqOW9V2mBcg70j5p6EnUDvw+odOUT+wDZCr/XBbzUNQ4VZXoABROSk6/HQlLVusgxpELWamviOGqpFk431PYxSwzO6Qh3JQKp3iRAaKEV/g1dgdXR2U1pJRZji1EyNa8gtAovTtEumsPjAeLOpC4sSXpFE7d7JfBlHAi38akYQgCDmVvfsBOyJcRRhVfNbcFwrzGQgWsIGHP9L4QZo6V1JUzovzkIV/oYZJpaAx1Pviz45ru80JoBiIx6/A9U+5uyT45cSb0TJ3D9lloqBeOkhIyiSpfHpXy/BICyqOJBjNIRPp69X6RhBCkLmPH2O234HaJeeYZ8CNlZX2vyxX7LFVn0wKmpg/UuVSS7Mno6oLes+g0xhUdfONYlwhn0PdwKoD6jV827vG918vlq0ZO8mn7h6mMqYmk3YA/yY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
