travis:
  secure:
    BINSTAR_TOKEN: ISoINFqBrqDmShJMDUfZjQJWDsUQRk08mAW3SRa+038RAMoo8HeskQChr19Ydf7HPdg9VKDAkr6HHYcbhNTPTIYzKQRCWNKfv/iTof9eV3hMFQG7yWfxUOOsBnaledFLWMiqUZav3zKCPZlerA7b0rCaJ10+q8yaI4Uy4yQ6Bkt9hU3TbURu0xmQfm/hdDDnGLzoAL9RxdFAQ6GEU8Kl7pITn1yzx3glb1JcM9j1u7pYdXMXiMR0JrxdDMWQuE2Z5zDrXQMUNV1s5JpIXbsAagx0agOS+2U5U9xBhBVlgzDjXpomveURTuBhakYUiDumwZbfIMgI3Zv/KvAVdbzR7/jpbEjeQ/fJAA9MOHsIzr8y/jXfDSeDIFkGnFXI6SYO2WNUd1doVuUpn+D0iIlsmG+cx6IFxoNuD6dPgDG9FJuzkSf2YLJ6NwhQetZI28IYqmi+AG9RS4Ic9hmWrfrv20EIIctykEdOWutbPRc+f1ki9IMqE6rVyjmDWV11hi76xSMrXNenRU3M5UvHfXD6tZKDu7YUBJbAFZgP6cpVQVOF4GNdQ8lve743NqU0FkDxSGK2bI42imvOAJsIAUsxfYTlq+JxVTsaZ5fZixQ0h0+baEKprE8helLiY80n5Z7K/OcsHfo0ZkYZ9zNc8EqJibVa3AkC7wmRzgbB2E/KZiw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
